name: Bug Report
description: File a bug report in Kipling method.
title: "[Bug]: Name the bug concisely as possible"
labels: ["bug"]
body:
  - type: checkboxes
    id: before-ask
    attributes:
      label: Before you ask
      description: Check these boxes before you asking.
      options:
        - label: "I have searched the issues and discussions"
        - label: "I have read the documentation"
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Tell us what you see.
      placeholder: "Describe the symptoms in chronological order.\n Media you can provide (screenshots, videos) will be helpful."
    validations:
      required: true
  - type: input
    id: who
    attributes:
      label: Which git version?
      description: The version you are running.
      placeholder: "Use `git -v` to show the version"
    validations:
      required: true
  - type: dropdown
    id: build
    attributes:
      label: Build from source
      options:
        - "no"
        - "yes"
      default: 0
  - type: input
    id: where
    attributes:
      label: Where did you see the bug?
      description: The environment you are running in.
      placeholder: "In Linux or MacOS: `uname -r`\nIn Windows: `ver`"
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How to reproduce
      description: Describe the steps to reproduce the bug.
      placeholder: "1. Step one\n2. Step two\n3. Step three"
    validations:
      required: true