name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: who
    attributes:
      label: Which version?
      description: Which version are you running?
      placeholder: "Use `git -v` to show the version"
    validations:
      required: true