name: Bug Report
description: Found something you weren't expecting?  Report it here!
labels: ["Unconfirmed Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
        NOTE: Please read the instructions below before filling the form.
  - type: markdown
    attributes:
      value: |
        1. Please write in English, this is the language all maintainers can speak and write.
        2. Please only use this form to submit bugs and **not** feature requests or questions.
        3. Please take a moment to check that your issue hasn't already been reported.
  - type: checkboxes
    id: before-ask
    attributes:
      label: Before you ask
      description: Check these boxes before you asking.
      options:
        - label: "I have searched the issues and discussions"
        - label: "I have read the documentation"
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Tell us what you see.
      placeholder: |
        Describe the symptoms in chronological order.
        Media you can provide (screenshots, videos) will be helpful.
    validations:
      required: true
  - type: input
    id: who
    attributes:
      label: Which git version?
      description: The version you are running.
      placeholder: "Use `git -v` to show the version"
    validations:
      required: true
  - type: dropdown
    id: build
    attributes:
      label: Build from source
      options:
        - "no"
        - "yes"
      default: 0
  - type: input
    id: where
    attributes:
      label: Where did you see the bug?
      description: The environment you are running in.
      placeholder: "In Linux or MacOS: `uname -r`\nIn Windows: `ver`"
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How to reproduce
      description: Describe the steps to reproduce the bug.
      placeholder: "1. Step one\n2. Step two\n3. Step three"
    validations:
      required: true