name: Bug Report
description: File a bug report.
title: "[Bug]: Name the bug concisely as possible"
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Tell us what you see.
      placeholder: Describe the symptoms in chronological order.
    validations:
      required: true
  - type: input
    id: who
    attributes:
      label: Which version?
      description: The version you are running.
      placeholder: "Use `git -v` to show the version"
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How to reproduce
      description: Describe the steps to reproduce the bug.
      placeholder: "1. Step one\n2. Step two\n3. Step three"
    validations:
      required: true