name: Codeonwers
on:
  workflow_dispatch:
jobs:
  code-owners:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create CODEOWNERS
        run: |
          echo "* @${{ github.repository_owner }}" > CODEOWNERS
      - name: Commit and push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull
          git add CODEOWNERS
          git commit -m "🤖 add CODEOWNERS"
          git push