name: gitleaks
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: "0 4 * * *" 
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}